# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[pdfapp.validators.validate_pdf_extension]),
        ),
    ]
