# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0002_auto_20170212_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='ready_html',
            field=models.BooleanField(default=False),
        ),
    ]
