# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0003_auto_20170218_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordination',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('denomination', models.CharField(max_length=60)),
                ('validity_year', models.IntegerField()),
                ('validity_trimester', models.CharField(choices=[('ene-mar', 'Enero-Marzo'), ('abr-jul', 'Abril-Julio'), ('jul-ago', 'Julio-Agosto (Intensivo)'), ('sep-dic', 'Septiembre-Diciembre')], max_length=7)),
                ('theory_hours', models.IntegerField(blank=True, null=True)),
                ('practice_hours', models.IntegerField(blank=True, null=True)),
                ('laboratory_hours', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('synoptic_content', models.TextField(blank=True)),
                ('methodological_strategies', models.TextField(blank=True)),
                ('evaluation_strategies', models.TextField(blank=True)),
                ('recommended_sources', models.TextField(blank=True)),
                ('coordination', models.ManyToManyField(blank=True, to='pdfapp.Coordination')),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdfapp.Department')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='program',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdfapp.Document'),
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfapp.Division'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='deanery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfapp.Deanery'),
        ),
    ]
