# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0004_auto_20170221_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordination',
            name='deanery',
        ),
        migrations.AddField(
            model_name='coordination',
            name='deanery',
            field=models.ManyToManyField(to='pdfapp.Deanery'),
        ),
    ]
