# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0005_auto_20170222_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.TextField(default='Error: You Need to get the Filename'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.TextField(default='Error: You Need to get the Path'),
        ),
    ]
