# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0006_auto_20170222_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.TextField(null=True),
        ),
    ]
