# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0007_auto_20170222_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.TextField(blank=True, default='Error: You Need to get the Filename'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
