# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0008_auto_20170222_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='validity_year',
            field=models.IntegerField(null=True),
        ),
    ]
