# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0008_auto_20170222_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='validity_trimester',
            field=models.CharField(choices=[('1: ene-mar', 'Enero-Marzo'), ('2: abr-jul', 'Abril-Julio'), ('3: jul-ago', 'Julio-Agosto (Intensivo)'), ('4: sep-dic', 'Septiembre-Diciembre')], max_length=7),
        ),
    ]
