# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0009_auto_20170223_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='credits',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_credits]),
        ),
        migrations.AlterField(
            model_name='program',
            name='evaluation_strategies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='laboratory_hours',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer]),
        ),
        migrations.AlterField(
            model_name='program',
            name='methodological_strategies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='practice_hours',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer]),
        ),
        migrations.AlterField(
            model_name='program',
            name='recommended_sources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='synoptic_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='theory_hours',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer]),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_year',
            field=models.IntegerField(validators=[pdfapp.validators.validate_program_years]),
        ),
    ]
