# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0009_auto_20170222_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdfapp.Department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='program',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_trimester',
            field=models.CharField(choices=[('ene-mar', 'Enero-Marzo'), ('abr-jul', 'Abril-Julio'), ('jul-ago', 'Julio-Agosto (Intensivo)'), ('sep-dic', 'Septiembre-Diciembre')], max_length=7, verbose_name='Trimestre'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_year',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
    ]
