# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0010_auto_20170225_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='html_text_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
