# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0011_auto_20170225_0046'),
        ('pdfapp', '0011_document_html_text_string'),
    ]

    operations = [
    ]
