# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0012_merge_20170225_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='credits',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_credits], verbose_name='Unidad de Créditos'),
        ),
        migrations.AlterField(
            model_name='program',
            name='evaluation_strategies',
            field=models.TextField(blank=True, null=True, verbose_name='Estrategias de Evaluación'),
        ),
        migrations.AlterField(
            model_name='program',
            name='laboratory_hours',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer], verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='program',
            name='methodological_strategies',
            field=models.TextField(blank=True, null=True, verbose_name='Estrategias Metodológicas'),
        ),
        migrations.AlterField(
            model_name='program',
            name='objectives',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='program',
            name='practice_hours',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer], verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='program',
            name='recommended_sources',
            field=models.TextField(blank=True, null=True, verbose_name='Fuentes de Información Recomendadas'),
        ),
        migrations.AlterField(
            model_name='program',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='program',
            name='synoptic_content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenidos Sipnóticos'),
        ),
        migrations.AlterField(
            model_name='program',
            name='theory_hours',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer], verbose_name='Horas de Teoría'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_trimester',
            field=models.CharField(choices=[('1: ene-mar', 'Enero-Marzo'), ('2: abr-jul', 'Abril-Julio'), ('3: jul-ago', 'Julio-Agosto (Intensivo)'), ('4: sep-dic', 'Septiembre-Diciembre')], max_length=7, verbose_name='Trimestre'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_year',
            field=models.IntegerField(null=True, validators=[pdfapp.validators.validate_program_years], verbose_name='Año'),
        ),
    ]
