# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0013_auto_20170225_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='laboratory_hours',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer], verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='program',
            name='practice_hours',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer], verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='program',
            name='theory_hours',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer], verbose_name='Horas de Teoría'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_trimester',
            field=models.CharField(choices=[('1: ene-mar', 'Enero-Marzo'), ('2: abr-jul', 'Abril-Julio'), ('3: jul-ago', 'Julio-Agosto (Intensivo)'), ('4: sep-dic', 'Septiembre-Diciembre')], max_length=10, verbose_name='Trimestre'),
        ),
    ]
