# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0014_auto_20170225_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='validity_trimester',
            field=models.CharField(blank=True, choices=[('1: ene-mar', 'Enero-Marzo'), ('2: abr-jul', 'Abril-Julio'), ('3: jul-ago', 'Julio-Agosto (Intensivo)'), ('4: sep-dic', 'Septiembre-Diciembre')], max_length=10, null=True, verbose_name='Trimestre'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_year',
            field=models.IntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_program_years], verbose_name='Año'),
        ),
    ]
