# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0015_auto_20170225_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='program',
            name='denomination',
            field=models.CharField(max_length=60, null=True, verbose_name='Denominación'),
        ),
    ]
