# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0018_auto_20170225_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='program',
            name='denomination',
            field=models.CharField(blank=True, max_length=60, verbose_name='Denominación'),
        ),
    ]
