# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0019_auto_20170225_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdfapp.Department', verbose_name='Departamento'),
        ),
    ]
