# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0023_auto_20170312_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='program',
            name='laboratory_hours',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer, pdfapp.validators.validate_max_hours], verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='program',
            name='practice_hours',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer, pdfapp.validators.validate_max_hours], verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='program',
            name='theory_hours',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_positive_integer, pdfapp.validators.validate_max_hours], verbose_name='Horas de Teoría'),
        ),
    ]
