# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 03:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0024_auto_20170314_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdfapp.Code', verbose_name='Código Departamento'),
        ),
        migrations.AlterField(
            model_name='program',
            name='number',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Debe estar formado por 3 o 4 dígitos.', regex='^\\d{3,4}$')], verbose_name='Código Número'),
        ),
    ]
