# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0026_auto_20170316_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('h_teoria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Teoría')),
                ('h_prac', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Práctica')),
                ('h_lab', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Laboratorio')),
                ('fecha_vigAno', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('fecha_vigTrim', models.CharField(blank=True, choices=[('0Ene-Mar', 'Enero-Marzo'), ('1Abr-Jul', 'Abril-Julio'), ('2Jul-Ago', 'Julio-Agosto (Intensivo)'), ('3Sep-Dic', 'Septiembre-Diciembre')], max_length=8, null=True, verbose_name='Fecha Vigencia Trimestre')),
                ('obj_g', models.TextField(blank=True, null=True, verbose_name='Objetivo general')),
                ('obj_e', models.TextField(blank=True, null=True, verbose_name='Objetivo específico')),
                ('contenidos', models.TextField(blank=True, null=True, verbose_name='Contenidos')),
                ('estrategias', models.TextField(blank=True, null=True, verbose_name='Estrategias')),
                ('estrat_eval', models.TextField(blank=True, null=True, verbose_name='Estrategias evaluativas')),
                ('fuentes', models.TextField(blank=True, null=True, verbose_name='Fuentes')),
                ('cronograma', models.TextField(blank=True, null=True, verbose_name='Cronograma')),
                ('sinoptico', models.TextField(blank=True, null=True, verbose_name='Contenidos Sipnóticos')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcoord', models.CharField(max_length=50, verbose_name='Nombre Coordinacion')),
                ('porasignar', models.BooleanField(default=True)),
                ('porvalidarD', models.BooleanField(default=True)),
                ('rechazadoC', models.BooleanField(default=False)),
                ('validadoC', models.BooleanField(default=False)),
                ('enviadoD', models.BooleanField(default=False)),
                ('devueltoDace', models.BooleanField(default=False)),
                ('fechaelab', models.DateTimeField(default=datetime.datetime.now)),
                ('credits', models.BooleanField(verbose_name='Unidad de Créditos')),
                ('h_teoria', models.BooleanField(default=False, verbose_name='Horas de Teoría')),
                ('h_prac', models.BooleanField(default=False, verbose_name='Horas de Práctica')),
                ('h_lab', models.BooleanField(default=False, verbose_name='Horas de Teoría')),
                ('trime', models.CharField(max_length=8, verbose_name='Trimestre')),
                ('ano', models.CharField(max_length=8, verbose_name='Año')),
                ('requisito_cre', models.BooleanField(default=False, verbose_name='Requisitos')),
                ('permiso_coord', models.BooleanField(default=False, verbose_name='Permisos')),
                ('tipo_materia', models.CharField(max_length=20, verbose_name='Tipo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfapp.Programa')),
            ],
        ),
    ]
