# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0026_merge_20170316_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='validity_trimester',
            field=models.CharField(blank=True, choices=[('Ene-Mar', 'Enero-Marzo'), ('Abr-Jul', 'Abril-Julio'), ('Jul-Ago', 'Julio-Agosto (Intensivo)'), ('Sep-Dic', 'Septiembre-Diciembre')], max_length=10, null=True, verbose_name='Trimestre propuesto'),
        ),
    ]
