# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0027_auto_20170316_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='credits',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[pdfapp.validators.validate_credits], verbose_name='Unidad de Créditos'),
        ),
        migrations.AlterField(
            model_name='program',
            name='laboratory_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[pdfapp.validators.validate_positive_integer, pdfapp.validators.validate_max_hours], verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='program',
            name='practice_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[pdfapp.validators.validate_positive_integer, pdfapp.validators.validate_max_hours], verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='program',
            name='theory_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[pdfapp.validators.validate_positive_integer, pdfapp.validators.validate_max_hours], verbose_name='Horas de Teoría'),
        ),
    ]
