# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0028_auto_20170316_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='validity_date_d',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_days_month], verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_date_m',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_date_y',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_program_years], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_program_years], verbose_name='Año propuesto'),
        ),
    ]
