# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0027_programa_solicitud'),
        ('pdfapp', '0029_auto_20170316_0313'),
    ]

    operations = [
    ]
