# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0030_merge_20170317_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='validity_date_d',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[pdfapp.validators.validate_days_month], verbose_name='Día'),
        ),
    ]
