# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0030_merge_20170317_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='denominacion',
            field=models.TextField(blank=True, verbose_name='Denominación'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_date_d',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[pdfapp.validators.validate_days_month], verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='program',
            name='validity_trimester',
            field=models.CharField(blank=True, choices=[('0Ene-Mar', 'Enero-Marzo'), ('1Abr-Jul', 'Abril-Julio'), ('2Jul-Ago', 'Julio-Agosto (Intensivo)'), ('3Sep-Dic', 'Septiembre-Diciembre')], max_length=10, null=True, verbose_name='Trimestre propuesto'),
        ),
    ]
