# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0031_auto_20170317_0125'),
        ('pdfapp', '0030_merge_20170317_0244'),
    ]

    operations = [
    ]
