# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0032_programa_creditos'),
        ('pdfapp', '0032_merge_20170317_0252'),
    ]

    operations = [
    ]
