# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0035_auto_20170330_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='edition_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_non_zero], verbose_name='No. Edición'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[pdfapp.validators.validate_years], verbose_name='Año'),
        ),
    ]
