# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0036_auto_20170331_0223'),
        ('pdfapp', '0037_auto_20170331_0207'),
    ]

    operations = [
    ]
