# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0038_merge_20170331_0510'),
        ('pdfapp', '0038_merge_20170331_0508'),
    ]

    operations = [
    ]
