"""
Command to insert the necessary academic units into the database.
Made by Carlos Infante
Last edit 02/23/2017
"""
from django.core.management.base import BaseCommand
from django.db import models
from pdfapp.models import Division
from pdfapp.models import Deanery
from pdfapp.models import Department
from pdfapp.models import Coordination
from pdfapp.models import Code

import sys

class Command(BaseCommand):
    help="Insert divisions, deaneries, departments, codes, and coordinations into the database"
    def handle(self, *args, **options):
        print("Please, ONLY run this one time. Else you will be inserting them manually")
        print("Do you want to clean the tables before insertion?")
        print("Be weary that duplicate data could be inserted otherwise")
        print("WARNING: This will wipe all data inserted into divisions, deaneries, departments, codes and coordinations tables")
        print("Delete? (y/n): ", end="")
        ans = input()
        if (ans.lower() == "y"):
            print("DELETING")
            Division.objects.all().delete()
            Deanery.objects.all().delete()
            Department.objects.all().delete()
            Coordination.objects.all().delete()
            print("Done")

        # Create divisions
        print("Adding data into the database...")
        fis_mat = Division.objects.create(name='División de Ciencias Físicas y Matemáticas')
        soc_hum = Division.objects.create(name='División de Ciencias Sociales y Humanidades')
        bio = Division.objects.create(name='División de Ciencias Biológicas')
        tec_adm = Division.objects.create(name='División de Ciencias y Tecnologías Administrativas e Industriales')
        act= Division.objects.create(name='Actividad especial')

        # Create Deaneries
        gen = Deanery.objects.create(name='Decanato de Estudios Generales')
        pro = Deanery.objects.create(name='Decanato de Estudios Profesionales')
        tec = Deanery.objects.create(name='Decanato de Estudios Tecnológicos')
        post = Deanery.objects.create(name='Decanato de Estudios de Postgrado')

        # Create Departments
        fs = Department.objects.create(name='Departamento de Física', division=fis_mat)
        qm = Department.objects.create(name='Departamento de Química', division=fis_mat)
        mc = Department.objects.create(name='Departamento de Mecánica', division=fis_mat)
        ma = Department.objects.create(name='Departamento de Matemáticas Puras y Aplicadas', division=fis_mat)
        ci = Department.objects.create(name='Departamento de Computación y Tecnología de la Información', division=fis_mat)
        co = Department.objects.create(name='Departamento de Cómputo Científico y Estadística', division=fis_mat)
        ec = Department.objects.create(name='Departamento de Electrónica y Circuitos', division=fis_mat)
        tf = Department.objects.create(name='Departamento de Termodinámica y Fenómenos de Transferencia', division=fis_mat)
        ct = Department.objects.create(name='Departamento de Conversión y Transporte de Energía', division=fis_mat)
        ps = Department.objects.create(name='Departamento de Procesos y Sistemas', division=fis_mat)
        mt = Department.objects.create(name='Departamento de Ciencias de los Materiales', division=fis_mat)
        gc = Department.objects.create(name='Departamento de Ciencias de la Tierra', division=fis_mat)

        cc = Department.objects.create(name='Departamento de Ciencia y Tecnología del Comportamiento', division=soc_hum)
        ll = Department.objects.create(name='Departamento de Lengua y Literatura', division=soc_hum)
        ce = Department.objects.create(name='Departamento de Ciencias Económicas y Administrativas', division=soc_hum)
        idm = Department.objects.create(name='Departamento de Idiomas', division=soc_hum)
        ff = Department.objects.create(name='Departamento de Filosofía', division=soc_hum)
        cs = Department.objects.create(name='Departamento de Ciencias Sociales', division=soc_hum)
        da = Department.objects.create(name='Departamento de Diseño Arquitectura y Artes Plásticas', division=soc_hum)
        pl = Department.objects.create(name='Departamento de Planificación Urbana', division=soc_hum)

        bc = Department.objects.create(name='Departamento de Biología Celular', division=bio)
        ea = Department.objects.create(name='Departamento de Estudios Ambientales', division=bio)
        pb = Department.objects.create(name='Departamento de Tecnología de Procesos Biológicos y Bioquímicos', division=bio)
        bo = Department.objects.create(name='Departamento de Biología de Organismos', division=bio)

        ts = Department.objects.create(name='Departamento de Tecnología de Servicios', division=tec_adm)
        ti = Department.objects.create(name='Departamento de Tecnología Industrial', division=tec_adm)
        fc = Department.objects.create(name='Departamento de Formación General y Ciencias Básicas', division=tec_adm)

        ep = Department.objects.create(name='Cursos en Cooperación (Carreras Largas)', division=act)
        et = Department.objects.create(name='Cursos en Cooperación (Carreras Cortas)', division=act)
        pg = Department.objects.create(name='Proyecto de Grado', division=act)
        td = Department.objects.create(name='Tesis Doctoral', division=act)
        teg = Department.objects.create(name='Trabajo Especial de Grado', division=act)
        tg = Department.objects.create(name='Trabajo de Grado (Postgrado)', division=act)
        usb = Department.objects.create(name='Trabajo de Grado (Pregrado)', division=act)

        # Create Coordinations
        d = Coordination.objects.create(name='Coordinación de Ciclo Básico')
        d.deanery.add(gen)
        d = Coordination.objects.create(name='Coordinación de Ciclo Profesional')
        d.deanery.add(gen)
        d = Coordination.objects.create(name='Coordinación de Formación General')
        d.deanery.add(gen)
        d = Coordination.objects.create(name='Coordinación de Ciclo de Iniciación Universitaria')
        d.deanery.add(gen)
        d = Coordination.objects.create(name='Coordinación de Química')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Matemática')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Biología')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Física')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Tecnología e Ingeniería Eléctrica')
        d.deanery.add(pro, tec)
        d = Coordination.objects.create(name='Coordinación de Tecnología e Ingeniería Electrónica')
        d.deanery.add(pro, tec)
        d = Coordination.objects.create(name='Coordinación de Ingeniería Mecánica')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Ingeniería Química')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Ingeniería de Computación')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Ingeniería Geofísica')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Ingeniería de Materiales')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Ingeniería de Producción y Organización Empresarial')
        d.deanery.add(pro, tec)
        d = Coordination.objects.create(name='Coordinación de Tecnología Mecánica, Mantenimiento Aeronáutico e Ingeniería de Mantenimiento')
        d.deanery.add(pro, tec)
        d = Coordination.objects.create(name='Coordinación de Ingeniería de Telecomunicaciones')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Arquitectura')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Estudios Urbanos')
        d.deanery.add(pro)
        d = Coordination.objects.create(name='Coordinación de Turismo, Hotelería y Hospitalidad')
        d.deanery.add(pro, tec)
        d = Coordination.objects.create(name='Coordinación de Comercio Exterior y Licenciatura en Comercio Internacional')
        d.deanery.add(pro, tec)
        d = Coordination.objects.create(name='Coordinación de Administración Aduanera')
        d.deanery.add(tec)
        d = Coordination.objects.create(name='Coordinación de Administración del Transporte y Organización Empresarial')
        d.deanery.add(tec)
        d = Coordination.objects.create(name='Ciencias Básicas y Aplicadas')
        d.deanery.add(post)
        d = Coordination.objects.create(name='Ciencias Sociales y Humanidades')
        d.deanery.add(post)
        d = Coordination.objects.create(name='Ingeniería y Tecnología')
        d.deanery.add(post)

        # Create codes
        d = Code.objects.create(code='CO', department=co)
        d = Code.objects.create(code='EP', department=ep)
        d = Code.objects.create(code='DFM', department=ep)
        d = Code.objects.create(code='ET', department=et)
        d = Code.objects.create(code='CI', department=ci)
        d = Code.objects.create(code='CIB', department=ci)
        d = Code.objects.create(code='BC', department=bc)
        d = Code.objects.create(code='BCB', department=bc)
        d = Code.objects.create(code='BO', department=bo)
        d = Code.objects.create(code='BOB', department=bo)
        d = Code.objects.create(code='MT', department=mt)
        d = Code.objects.create(code='CMT', department=mt)
        d = Code.objects.create(code='GC', department=gc)
        d = Code.objects.create(code='CE', department=ce)
        d = Code.objects.create(code='CEA', department=ce)
        d = Code.objects.create(code='CS', department=cs)
        d = Code.objects.create(code='CSA', department=cs)
        d = Code.objects.create(code='CSX', department=cs)
        d = Code.objects.create(code='CSY', department=cs)
        d = Code.objects.create(code='CSZ', department=cs)
        d = Code.objects.create(code='EGS', department=cs)
        d = Code.objects.create(code='CC', department=cc)
        d = Code.objects.create(code='CCE', department=cc)
        d = Code.objects.create(code='CT', department=ct)
        d = Code.objects.create(code='CTE', department=ct)
        d = Code.objects.create(code='DA', department=da)
        d = Code.objects.create(code='DAP', department=da)
        d = Code.objects.create(code='DAA', department=da)
        d = Code.objects.create(code='EC', department=ec)
        d = Code.objects.create(code='EYC', department=ec)
        d = Code.objects.create(code='EA', department=ea)
        d = Code.objects.create(code='EAD', department=ea)
        d = Code.objects.create(code='FF', department=ff)
        d = Code.objects.create(code='FL', department=ff)
        d = Code.objects.create(code='FS', department=fs)
        d = Code.objects.create(code='FSI', department=fs)
        d = Code.objects.create(code='FIS', department=fs)
        d = Code.objects.create(code='FC', department=fc)
        d = Code.objects.create(code='FCR', department=fc)
        d = Code.objects.create(code='FCA', department=fc)
        d = Code.objects.create(code='FCB', department=fc)
        d = Code.objects.create(code='FCC', department=fc)
        d = Code.objects.create(code='FCE', department=fc)
        d = Code.objects.create(code='FCF', department=fc)
        d = Code.objects.create(code='FCG', department=fc)
        d = Code.objects.create(code='FCH', department=fc)
        d = Code.objects.create(code='FCI', department=fc)
        d = Code.objects.create(code='FCL', department=fc)
        d = Code.objects.create(code='FCX', department=fc)
        d = Code.objects.create(code='FCZ', department=fc)
        d = Code.objects.create(code='FCW', department=fc)
        d = Code.objects.create(code='ID', department=idm)
        d = Code.objects.create(code='IDM', department=idm)
        d = Code.objects.create(code='LL', department=ll)
        d = Code.objects.create(code='LLA', department=ll)
        d = Code.objects.create(code='LLB', department=ll)
        d = Code.objects.create(code='LLC', department=ll)
        d = Code.objects.create(code='LLE', department=ll)
        d = Code.objects.create(code='EGL', department=ll)
        d = Code.objects.create(code='MA', department=ma)
        d = Code.objects.create(code='MAT', department=ma)
        d = Code.objects.create(code='MC', department=mc)
        d = Code.objects.create(code='MEC', department=mc)
        d = Code.objects.create(code='PL', department=pl)
        d = Code.objects.create(code='PLX', department=pl)
        d = Code.objects.create(code='PLY', department=pl)
        d = Code.objects.create(code='PS', department=ps)
        d = Code.objects.create(code='PRS', department=ps)
        d = Code.objects.create(code='QM', department=qm)
        d = Code.objects.create(code='QIM', department=qm)
        d = Code.objects.create(code='PB', department=pb)
        d = Code.objects.create(code='TS', department=ts)
        d = Code.objects.create(code='TSX', department=ts)
        d = Code.objects.create(code='TI', department=ti)
        d = Code.objects.create(code='TF', department=tf)
        d = Code.objects.create(code='TFT', department=tf)
        d = Code.objects.create(code='PG', department=pg)
        d = Code.objects.create(code='TD', department=td)
        d = Code.objects.create(code='TEG', department=teg)
        d = Code.objects.create(code='TG', department=tg)
        d = Code.objects.create(code='USB', department=usb)

        print("Done")
